PashaKlybik/ASM-753505-2018

ilyakrasnou/lab1.asm

Вариант 6
Если a OR (a + 1) = b то
Результат = (a * b + c) % d
Иначе
Если a AND b = c OR d то
Результат = b AND (b - 1)
Иначе
Результат = c % d + b * a

[Краснов Илья] - Лабораторная работа №1

---

ilyakrasnou/lab2.asm

[Краснов Илья] - Лабораторная работа 2

---

ZhenyaAlhovsky/lab1.asm

3) Если a * c + b * d = a * d + b * c то
Результат = a ^ 2
Иначе
Если a > c то
Результат = (с AND b)
Иначе
Результат = a – (b OR c)

Лабораторная работа 1 [Альховский Евгений]

---

edadasko/lab1.asm

Если a ^ 3 > b ^ 2 то
------Если c * d = a / b то
---------Результат = a AND b
------Иначе
---------Результат = с
Иначе
------Результат = с * d + b

[Адасько Эдуард] Лабораторная работа 1 (Вариант 1)

---

VadimOliseichik/Lab1.asm

В каждом из заданий переменные a, b, c, d определяются в сегменте данных и имеют размерность слово. Необходимо выполнить над ними заданные арифметические и логические операции, а результат поместить в регистр AX. При выполнении умножения считаем, что результат вмещается в слово. При выполнении деления считаем, что оно целочисленное. Выполнение программы необходимо показать в Отладчике. 
1) Если a ^ 3 > b ^ 2 то
Если c * d = a / b то
Результат = a AND b
Иначе
Результат = с
Иначе
Результат = с * d + b

Лабораторная работа №1 (Вариант 1). [Олисейчик Вадим] 

---

deidzen/lab1.asm

Вариант 7. Найти максимум между a\*b, b\*c, c\*d, d\*a.

[Лагун Алексей] - Лабораторная работа №1

---

DmitryBrezin/lr1.asm

В каждом из заданий переменные a, b, c, d определяются в сегменте данных и имеют размерность слово. Необходимо выполнить над ними заданные арифметические и логические операции, а результат поместить в регистр AX. При выполнении умножения считаем, что результат вмещается в слово. При выполнении деления считаем, что оно целочисленное. Выполнение программы необходимо показать в Отладчике.
5) Если a AND (a - 1) = b то
Если d > c + b то
Результат = c % d + c / d
Иначе
Результат = c XOR d
Иначе
Результат = b OR (b + 1)

Лабораторная работа №1 [Брезин Дмитрий] 

---

edadasko/lab3.asm

[Адасько Эдуард] Лабораторная работа 3

---

IvanChibisov/lab3.asm

Задание аналогично ЛР2 , только со знаковыми числами.

Добавляю 3 ЛР[Чибисов И.В.]

---

IvanChibisov/lab2.asm

Необходимо ввести 2 числа и выполнить деление первого на второе. Проконтроллировать ввод. После ввода числа, сразу же вывести его на экран. Вывести результат деления.
Реализованы Backspace и Esc.

Добавляю 2 ЛР[Чибисов И.В.]

---

ZhenyaAlhovsky/Lab2.asm

Лабораторная работа 2 [Альховский Евгений]

---

Sanchous19/Lab4.asm

Найти и показать все слова, которые являются частями других слов этой строки.

[Лесун Александр] - Лабораторная работа №4

---

VadimOliseichik/Lab2.asm

Задание:
нельзя вводить не цифры, нельзя, например, ввести 70000.
3) в функции main пользователь вводит делимое, затем сразу же осуществляется …

Лабораторная работа №2. [Олисейчик Вадим] 

---

VadimOliseichik/Lab3.asm

Лабораторная работа 2
Задание:
нельзя вводить не цифры, нельзя, например, ввести 70000.
3) в функции main пользователь вводит делимое, затем …

Лабораторная работа №3 [Олисейчик Вадим]

---

khavlaren/lab1.asm

Исправлены ошибки.
Вариант 8, условие в коде.

[Харитонов Владимир] Лабораторная работа 1.

---

khavlaren/lab2.asm

Последний вариант во втором commit'е.

[Харитонов Владимир] Лабораторная работа 2.

---

OlegZhdanenya/lab2.asm

[Oleg Zhdanenya]ЛР2

---

ilyakrasnou/lab4.asm

Вариант 16
Поменять местами наибольшее и наименьшее по длине слово.

[Краснов Илья] - Лабораторная работа 4

---

ilyakrasnou/lab5.asm

Вариант 6
Есть ввод с файла, вывод в файл, ограничение на размер массива - 10*10
Дополнительное задание на более высокую оценку: сделать ввод исходных матриц из файла, вывод результата в …

[Краснов Илья] - Лабораторная работа 5

---

Sanchous19/Lab5.asm

Дополнительное задание на более высокую оценку: сделать ввод исходных матриц из файла, вывод результата в файл (название файлов можно задать в сегменте данных, например "input.txt" …

[Лесун Александр] - Лабораторная работа №5

---

ToT-CaMbIu/Lab1App.asm

Лабораторная работа №1 [Григорьев Кирилл]

---

Lab2Asm.asm

Задание:
1)написать процедуру для вывода числа размерностью слово из регистра AX на экран
2)написать процедуру для ввода числа с клавиатуры в регистр AX …

[Григорьев Кирилл] Лабораторная работа №2

---

ZhenyaAlhovsky/lab4.asm

Лабораторная работа 4
Необходимо ввести строку с клавиатуры, сделать ее обработку согласно заданию и показать результат на экране. При выполнении работы необходимо использовать хотя бы одну из [команд для работы с цепочками](http://kit.znu.edu.ua/eDoc/Arch/assembl/guide/Lesson/Lesson11/Les_11.htm). Считается, что строка состоит из слов, разделенных произвольным числом пробелов (за исключением вариантов 5, 6, 8, 9). Пробелы также могут располагаться перед первым словом и после последнего слова.
Вариант:
2) Найти и показать все слова, в которых идут подряд две гласные буквы.

Лабораторная работа 4 [Альховский Евгений]

---

IvanChibisov/lab4.asm

Необходимо ввести строку с клавиатуры, сделать ее обработку согласно заданию и показать результат на экране. При выполнении работы необходимо использовать хотя бы одну из [команд для работы с цепочками]. Считается, что строка состоит из слов, разделенных произвольным числом пробелов (за исключением вариантов 5, 6, 8, 9). Пробелы также могут располагаться перед первым словом и после последнего слова.
12) Удалить из строки слова, не являющиеся палиндромами

Лабораторная работа №4 [Чибисов И.В.]

---

VadimOliseichik/lab5.asm

1) Вводится размерность N <= 3 и квадратная матрица размерности NxN. Необходимо найти определитель этой матрицы.

Лабораторная работа №5 [Олисейчик Вадим]

---

lab3/Lab3Asm.asm

Задание:
1.написать процедуру для вывода знакового числа размерностью слово из регистра AX на экран
2.написать процедуру для ввода знакового числа с клавиатуры в регистр AX
3.в …

[Григорьев Кирилл] Лабораторная работа №3

---

Lab4/Lab4App.asm

9 вар.Пользователь вводит строку, состоящую только из символов "(){}[]". Проверить, является ли данная скобочная последовательность корректной.

[Григорьев Кирилл] Лабораторная работа №4

---

ChueshkovEgor/lab3.asm

Лабораторная работа 3                  
Задание:
последний введенный символ) …

[Чуешков Егор] Лабораторная работа 3 

---

Meleron/lr5.asm

Вводятся размерности N и M и матрица размерности NxM. Поменять местами максимальный элемент, распложенный выше главной диагонали, и минимальный элемент, расположенный не выше главой диагонали.

[Троцкий Даниил] - Лабораторная работа №5

---

edadasko/l4.asm

Лабораторная работа 4:
Вариант 1 - Посчитать, сколько слов начинается с гласной буквы.

[Адасько Эдуард] Лабораторная работа 4 (Вариант 1)

---

edadasko/l5.asm

Вариант 1:
1) Вводится размерность N <= 3 и квадратная матрица размерности NxN. Необходимо найти определитель этой матрицы.
Осуществлен ввод исходной матрицы из файла, вывод результата в файл.

[Адасько Эдуард] - Лабораторная работа №5

---

OlegZhdanenya/lab3.asm

[Oleg Zhdanenya] Lab3

---

khavlaren/lab4.asm

Вариант 10.
Найти и показать самое короткое и самое длинное слово в строке.
На выводе (для min и max): слово, индекс начала слова, длина слова (на всякий).

[Харитонов Владимир] Лабораторная работа 4.

---

ChueshkovEgor/lab4.asm

Удалить из строки все повторяющиеся символы (Оставить только первый символ из повторяющихся)

[Чуешков Егор] Лабораторная работа 4

---

ZhenyaAlhovsky/lab5.asm

Лабораторная работа 5
Дополнительное задание на более высокую оценку: сделать ввод исходных матриц из файла, вывод результата в файл (название файлов можно задать в сегменте данных, …

Лабораторная работа 5 [Альховский Евгений]

---

ZhenyaAlhovsky/lab3.asm

Лабораторная работа 3 [Альховский Евгений]

---

OlegZhdanenya/lab4.asm

Необходимо ввести строку с клавиатуры, сделать ее обработку согласно заданию и показать результат на экране. При выполнении работы необходимо использовать хотя бы одну из [команд для работы с цепочками](http://kit.znu.edu.ua/eDoc/Arch/assembl/guide/Lesson/Lesson11/Les_11.htm). Считается, что строка состоит из слов, разделенных произвольным числом пробелов (за исключением вариантов 5, 6, 8, 9). Пробелы также могут располагаться перед первым словом и после последнего слова.
Вариант 11 
Найти в строке самое частое слово и показать его на экране.

[Oleg Zhdanenya] lab4

---

PaulSeptember/lab1.ASM

Вариант 2
Если a AND b = c ^ 4 то
Результат = с / d / b + a
Иначе
Если c + b = a ^ 3 + b ^ 3 то
Результат = a XOR (b + c)
Иначе
Результат = b >> 3

[Каменко Павел] - Лабораторная работа 1

---

PaulSeptember/lab2.asm

В функции main пользователь вводит делимое, затем сразу же осуществляется вывод делимого на экран, затем пользователь вводит делитель, далее осуществляется вывод делителя на экран, затем осуществляется деление и вывод результата деления на экран.

[Каменко Павел] - Лабораторная работа 2

---

PaulSeptember/lab3.asm

Вторая лаба , только умеет в числа со знаком

[Каменко Павел] - Лабораторная работа 3

---

deidzen/lab2.asm

[Лагун Алексей] - Лабораторная работа №2

---

ilyakrasnou/lab6.asm

6) Перекрыть девятую функцию прерывания 21h таким образом, чтобы в выводимой строке все гласные буквы были удалены.

[Краснов Илья] Лабораторная работа 6

---

IvanChibisov/lab5.asm

Лабораторная работа 5
Дополнительное задание на более высокую оценку: сделать ввод исходных матриц из файла, вывод результата в файл (название файлов можно задать в сегменте данных, …

Лабораторная работа №5[Чибисов И.В.]

---

anduda/lab5.asm

Лабораторная работа 5
Дополнительное задание на более высокую оценку: сделать ввод исходных матриц из файла, вывод результата в файл (название файлов можно задать в сегменте данных, …

lab5 Сташкевич

---

anduda/lab4.asm

7) Удалить из строки все слова, длины которых меньше n (n берется из сегмента данных).

lab4 сташкевич

---

deidzen/lab3.asm

Лабораторная работа 3                  
Задание:
последний введенный символ) …

[Лагун Алексей] - Лабораторная работа №3

---

PaulSeptember/lab5.asm

Лабораторная работа 5
Пятое задание посвящается двухмерным массивам.
Каждый из них является прямоугольным, если не указано обратное (количество строк может быть отличным от количества столбцов). Для задания массива необходимо ввести количество строк, затем количество столбцов и затем все элементы. 
Для ввода и вывода чисел использовать функции из 3 работы (работа со знаковыми числами), для простоты считать, что ввод всегда корректный (т.е. можно убрать все проверки на некорректность  из функций). При выводе на экран элементы одного столбца матрицы необходимо показывать друг под другом (разделять элементы символом табуляции).
Дополнительное задание на более высокую оценку: сделать ввод исходных матриц из файла, вывод результата в файл (название файлов можно задать в сегменте данных, …

[Каменко Павел] - Лабораторная работа 5

---

SingularityUrBrain/lab5_git.asm

Пятое задание посвящается двухмерным массивам. Каждый из них является прямоугольным, если не указано обратное (количество строк может быть отличным от количества столбцов).
Дополнительное задание на более высокую оценку: сделать ввод исходных матриц из файла, вывод результата в файл (название файлов можно задать в сегменте данных, например "input.txt" "output.txt").
3) Вводятся размерности N и M и матрица размерности NxM. Необходимо найти сумму элементов, находящихся в четных столбах и показать эту сумму на экране.
[Readme.txt](https://github.com/PashaKlybik/ASM-753505-2018/files/2587104/Readme.txt)

[Камзеев Никита] Лабораторная работа №5

---

khavlaren/lab5.asm

Задание:
8) Вводятся размерности N и M, матрица размерности NxM, числа K и L. Удалить из матрицы строку(если K = 0) или столбец(если K = 1) под номером L, сдвинуть оставшиеся элементы на место удаленных.

[Харитонов Владимир] Лабораторная работа 5.

---

VadimOliseichik/main.cpp

Разработка оконного приложения под платформу Win32
Создать оконное приложение, в котором на главном окне будет кнопка Clear. При щелчке мышью в любую точку нашего окна необходимо нарисовать небольшое изображение с центром в этой точке (например, елочку или домик). Нажатие на кнопку Clear должно очищать наше окно. Работу надо выполнять без библиотек типа Windows Forms, а напрямую используя функции работы с окнами.

Лабораторная работа 7 [Олисейчик Вадим]

---

Sanchous19/LR6.asm
Sanchous19/install.asm

Необходимо перекрыть указанный в задании обработчик прерывания и заставить его выполнять нужные действия. В большинстве случаев необходим вызов предыдущего обработчика. Также должна быть отдельная небольшая программа, демонстрирующая работу перекрытого обработчика.
Программа должна состоять из резидентной части и инсталяционной части. Первая из них отвечает за работу с перекрываемым прерыванием. А инсталяционная часть должна вызываться при старте программы и отвечать за установку обработчиков.
Инсталяционная часть должна уметь прочитать командную строку:
а) если нам не передается параметров:
- если обработчик уже установлен: выдать сообщение об этом и выйти из программы
- если обработчик еще не установлен: сохранить адрес старого обработчика, установить наш обработчик, выйти из программы, …

[Лесун Александр] - Лабораторная работа №6

---

SingularityUrBrain/lab4_git.asm

Необходимо ввести строку с клавиатуры, сделать ее обработку согласно заданию и показать результат на экране.
Удалить все слова, которые начинаются с гласной буквы.

[Камзеев Никита] Лабораторная работа 4

---

ZhenyaAlhovsky/Win32Project1.cpp

Лабораторная работа 7
Разработка оконного приложения под платформу Win32
Создать оконное приложение, в котором на главном окне будет кнопка Clear. При щелчке мышью в любую точку нашего окна необходимо нарисовать небольшое изображение с центром в этой точке (например, елочку или домик). Нажатие на кнопку Clear должно очищать наше окно. Работу надо выполнять без библиотек типа Windows Forms, а напрямую используя функции работы с окнами.

Лабораторная работа 7 [Альховский Евгений]

---

Evgeniu364/laba4.asm

Необходимо ввести строку с клавиатуры, сделать ее обработку согласно заданию и показать результат на экране. При выполнении работы необходимо использовать хотя бы одну из команд для работы с цепочками.
Удалить из строки все повторяющиеся символы (Оставить только первый символ из повторяющихся).

[Евгений Ботвинников]laba4

---

edadasko/Lab7.cpp

Лабораторная работа 7
Разработка оконного приложения под платформу Win32
Создать оконное приложение, в котором на главном окне будет кнопка Clear. При щелчке мышью в любую точку нашего окна необходимо нарисовать небольшое изображение с центром в этой точке (например, елочку или домик). Нажатие на кнопку Clear должно очищать наше окно. Работу надо выполнять без библиотек типа Windows Forms, а напрямую используя функции работы с окнами.

[Адасько Эдуард] Лабораторная работа 7

---

edadasko/l6.asm

Вариант 1: 
Перекрыть прерывание клавиатуры таким образом, чтобы буквы a, b, c, d, e заменялись соответственно на цифры 1, 2, 3, 4, 5.

[Адасько Эдуард] Лабораторная работа 6

---

ChueshkovEgor/lab5.asm

Вводится размерность N <= 3 и квадратная матрица размерности NxN. Необходимо найти определитель этой матрицы.

[Чуешков Егор] Лабораторная работа 5

---

deidzen/lab5.asm

Дополнительное задание на более высокую оценку: сделать ввод исходных матриц из файла, вывод результата в файл (название файлов можно задать в сегменте данных, например "input.txt" …

[Лагун Алексей] - Лабораторная работа №5

---

ToT-CaMbIu/ProgramPart.asm
ToT-CaMbIu/TsrPart.asm

[Григорьев Кирилл] Лабораторная работа №6

---

SingularityUrBrain/lab6_git.asm

Перекрыть прерывание клавиатуры таким образом, чтобы при нажатии клавиш F1, F2, F3, F4 и F5 в буфер клавиатуры попадали слова HELP, SAVE, OPEN, EDIT, COPY.

[Камзеев Никита] Лабораторная работа №6

---

ZhenyaAlhovsky/lab6.asm

Лабораторная работа 6
Необходимо перекрыть указанный в задании обработчик прерывания и заставить его выполнять нужные действия. В большинстве случаев необходим вызов предыдущего обработчика. Также должна быть отдельная небольшая программа, демонстрирующая работу перекрытого обработчика. 
Программа должна состоять из резидентной части и инсталяционной части. Первая из них отвечает за работу с перекрываемым прерыванием. А инсталяционная часть должна вызываться при старте программы и отвечать за установку обработчиков.
Инсталяционная часть должна уметь прочитать командную строку:
а) если нам не передается параметров:
- если обработчик уже установлен: выдать сообщение об этом и выйти из программы
- если обработчик еще не установлен: сохранить адрес старого обработчика, установить наш …

Лабораторная работа 6 [Альховский Евгений]

---

DmitryBrezin/lr4.asm

Лабораторная работа 4
Необходимо ввести строку с клавиатуры, сделать ее обработку согласно заданию и показать результат на экране. При выполнении работы необходимо использовать хотя бы одну из [команд для работы с цепочками](http://kit.znu.edu.ua/eDoc/Arch/assembl/guide/Lesson/Lesson11/Les_11.htm). Считается, что строка состоит из слов, разделенных произвольным числом пробелов (за исключением вариантов 5, 6, 8, 9). Пробелы также могут располагаться перед первым словом и после последнего слова.
Варианты:
5) Заменить последовательности из нескольких пробелов одним.

[Дмитрий Брезин] Лабораторная работа 4

---

kladaFOX/lab3.asm

Лабораторная работа 3 Клапаток И.А.

---

lab5.asm

[Oleg Zhdanenya] lab5

---

ElephantT/lab1.asm

Signed-off-by: Alexandr Doubeikovsky <seaflowerelephant@gmail.com>

[Дубейковский Александр] Лабораторная работа 1

---

anduda/LR6.asm

перекрыть прерывание клавиатуры таким образом чтобы вместо гласных выводились следующие по алфавиту

Лабораторная работа 6 Сташкевич А.С.

---

kladaFOX/lab4.asm

Поменять в строке первое слово с последним, второе с предпоследним и так далее.

Лабораторная работа 4 Клапаток И.А.

---

deidzen/lab4.asm

Лабораторная работа 4
Необходимо ввести строку с клавиатуры, сделать ее обработку согласно заданию и показать результат на экране. При выполнении работы необходимо использовать хотя бы одну из команд для работы с цепочками. Считается, что строка состоит из слов, разделенных произвольным числом пробелов (за исключением вариантов 5, 6, 8, 9). Пробелы также могут располагаться перед первым словом и после последнего слова.
17) В программе хранится 3 строки: A, B (длины строк A и B одинаковы), C. В введенной пользователем строке удалить все символы, встречающиеся в строке С, и заменить все символы, встречающиеся в строке А, соответствующими символами строки B.

[Лагун Алексей] - Лабораторная работа №4

---

PaulSeptember/lab4.asm

Квест : Удалить все непалиндромы из строки

[Каменко Павел] Лабораторная работа 4

---

Izigraim/lab1.asm

7) найти максимальное ab,bc,cd,da

[Врублевский Илья] Лабораторная работа 1

---

jokuinn/lr1.asm

Если a * c + b * d = a * d + b * c ,то
Результат = a ^ 2
Иначе
Если a > c то
Результат = (с AND b)
Иначе
Результат = a – (b OR c)

[Реут Макс(поставьте допуск)]-Лабораторная работа 1

---

lab3.asm

1) написать процедуру для вывода знакового числа размерностью слово из регистра AX на экран на входе число в регистре AX на выходе это число на экране все задействованные регистры должны быть сохранены в процедуре
3) в …

[Врублевский Илья] Лабораторная работа 3

---

kladaFOX/lab5.asm

Ввести соответствующие размерности и две матрицы размерности NxK и LxM. Необходимо перемножить данные матрицы и результат показать на экране.

Лабораторная работа 5 Клапаток И.А.

---

Izigraim/lab2.asm

1. написать процедуру для вывода числа размерностью слово из регистра AX на экран на входе число в регистре AX на выходе это число на экране
2. написать процедуру для ввода числа с клавиатуры в регистр AX
последний …

[Врублевский Илья] Лабораторная работа 2

---

kladaFOX/lab6.asm

Перекрыть прерывание клавиатуры таким образом, чтобы все гласные буквы заменялись на следующие по алфавиту.

Лабараторная работа 6 Клапаток И.А

---

mikulichegor/1.asm

Написать программу, которая помещает в регистр AX наибольшее из 4 чисел.

Лабораторная Работа №1 [Микулич Егор]

---

ChueshkovEgor/lab6.asm

Перекрыть прерывание клавиатуры таким образом, чтобы буквы a, b, c, d, e заменялись соответственно на цифры 1, 2, 3, 4, 5.

[Чуешков Егор] Лабораторная работа 6

---

Evgeniu364/lab6.asm

Перекрыть девятую функцию прерывания 21h, чтобы в выводимой строке не было гласных букв.

[Ботвинников Евгений] Лаба № 6(версия 2.0)

---

Izigraim/lab4.asm

7. Удалить из строки все слова, длины которых меньше n (n берется из сегмента данных).
(Залил в свою папку.)

[Врублевский Илья] Лабораторная работа 4
